# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: swift test -v
    - name: Build app
      run: swift build -v
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: Jiwe
        path: .build/debug/Jiwe
    
